# MODIFY these settings

url: http://dh-box.github.io
name: DH Box
description: A portable, customized<br>Linux environment for<br>Digital Humanities learners
blog_name: DH Box
blog_description: has a blog
timezone: America/New_York

my_email: hkellaway@gc.cuny.edu
my_site_author_name: Harlan Kellaway
my_site_author_url: http://hkellaway.github.io
my_license: Licensed under Apache License v2.0
my_license_url: http://apache.org/licenses/LICENSE-2.0
my_template_name: Based on a  Theme by Start Bootstrap
my_template_url: http://startbootstrap.com/
my_headerimage_url: http://thepatternlibrary.com/
my_headerimage_name: Header image by The Pattern Library

my_search_engine_id_google: 001082080759982814974:iugunkxoumg
my_email_subscription_url: http://feedburner.google.com/fb/a/mailverify?uri=DHBoxBlog

is_github_ribbon_displayed: true
is_site_author_displayed: true
is_copyright_displayed: false
is_headerimagecred_displayed: true
is_blog_pagination_on: true
is_blog_printbutton_displayed: true
is_blog_postshare_displayed: true
is_socialmedia_widget_displayed: true
is_search_displayed: true
is_subscribe_displayed: true
is_warning_displayed: true
is_footermenu_displayed: true

my_label_toggle_navigation: Toggle Navigation
my_label_findoutmore: Find Out More
my_label_subscribebutton: Subscribe <i class="icon icon-envelope"></i>
my_label_socialmedia: Connect&#58;
my_delimiter_socialmedia: //
my_label_blog_post_list: Blog Posts
my_label_post_share: Share&#58;&nbsp;
my_label_warning: Site under construction! Visit <a class="alert-link" href="http://dhbox.commons.gc.cuny.edu/" target="_blank">DH Box Blog</a> for the latest information about DH Box.
 
github_ribbon_color: orange # can be blue, orange, gray, green, red
github_repo_url: https://github.com/hkellaway/Simple-Jekyll-Bootstrap-Theme

# DO NOT modify these without understanding why - it may have unintended consequences!

markdown: redcarpet
pygments: true

permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "blog/page:num"

my_blog_subpath: /blog/
my_images_subpath: /images_png/
my_images_filetype: .png

jekyll_url: http://jekyllrb.com/
github_ribbon_image_stub: github_ribbon_
bootstrap_noicons_cdn_url: //netdna.boostrapcdn.com/twitter-bootstrap/2.3.1/css/boostrap-combined.no-icons.min.css/
bootstrap_fontawesome_icons_cdn_url: //netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css
icons_url: http://fontawesome.io/
icons_label: Icons by FontAwesome
